import styles from "./styles/global.module.scss";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={styles.html}>
      <body className={styles.body}>
        <div className={styles.content}>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
